"""PPO self-play trainer with an opponent pool (random + greedy + frozen snapshots).

Each env plays one game. At reset an opponent is sampled: with probability `self_play_prob`
the latest policy plays both seats; otherwise an entry of the pool is drawn uniformly and the
learner takes a random seat. Reward is +1/-1/0 at the end of the game only.

Notes on the data this produces:
* Mirror games record both seats, so they supply roughly 2/3 of the transitions even though
  they are half of the games (the 50/50 split is over opponents sampled per game).
* Decisions where END_TURN is the only legal action are played without being recorded (they
  carry no policy gradient).
* Only finished games enter a batch. Games still running at the end of collect() continue in
  the next one, so a share of each batch was generated by the previous policy; the stored
  behaviour log-probs make the PPO ratio the correct importance weight for those samples.
"""
from __future__ import annotations

import copy
import json
import os
import random
import time
import warnings
from collections import defaultdict, deque
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Optional

import numpy as np
import torch

from ..agents.greedy_agent import GreedyAgent
from ..agents.random_agent import RandomAgent
from ..cards import GameConfig, load_ruleset
from ..engine import DRAW, Game
from ..features import ObservationEncoder
from .network import NumpyPolicy, PolicyValueNet

TRAIN_SEED_BASE = 1_000_000_000   # training deals never overlap eval.py's default seeds (0..)
TRAIN_SEEDS_PER_RUN = 10_000_000  # deal seeds reserved per --seed value (0 <= seed < 100)
QUICK_EVAL_SEED_BASE = 2_000_000_000


@dataclass
class PPOConfig:
    run_dir: str = "runs/ppo"
    seed: int = 0
    total_updates: int = 800
    num_envs: int = 128
    batch_steps: int = 16384      # learner transitions per update
    epochs: int = 4
    minibatch: int = 2048
    lr: float = 3e-4
    lr_final_frac: float = 0.1    # linear LR decay to lr * lr_final_frac
    gamma: float = 0.997
    gae_lambda: float = 0.95
    clip: float = 0.2
    ent_coef: float = 0.01
    vf_coef: float = 0.5
    max_grad_norm: float = 0.5
    target_kl: float = 0.03       # stop the epoch loop early if exceeded (0 = off)
    hidden: tuple = (256, 256)
    snapshot_every: int = 10      # N: freeze a snapshot into the pool every N updates
    max_snapshots: int = 30       # oldest snapshots are dropped beyond this (random/greedy stay)
    self_play_prob: float = 0.5
    eval_every: int = 10
    eval_deals: int = 200         # quick duplicate eval vs greedy (2 games per deal)
    torch_threads: int = 4
    extra: dict = field(default_factory=dict)


class Opponent:
    def __init__(self, kind: str, name: str, agent=None, net: Optional[PolicyValueNet] = None,
                 path: Optional[str] = None):
        self.kind, self.name, self.agent, self.net, self.path = kind, name, agent, net, path
        self.policy = NumpyPolicy(net) if net is not None else None  # cheap batched inference


class EnvSlot:
    __slots__ = ("game", "opp", "learner_seats", "traj")

    def __init__(self, game: Game):
        self.game = game
        self.opp: Optional[Opponent] = None
        self.learner_seats: tuple = ()
        self.traj: dict = {}


class PPOTrainer:
    def __init__(self, cfg: PPOConfig, config: Optional[GameConfig] = None):
        if not 0 <= cfg.seed < (QUICK_EVAL_SEED_BASE - TRAIN_SEED_BASE) // TRAIN_SEEDS_PER_RUN:
            raise ValueError("seed must be in [0, 100) so training deals stay disjoint from eval deals")
        for name in ("snapshot_every", "num_envs", "batch_steps", "minibatch", "epochs", "total_updates"):
            if getattr(cfg, name) < 1:
                raise ValueError(f"{name} must be >= 1")
        if cfg.eval_every and cfg.eval_deals < 1:
            raise ValueError("eval_deals must be >= 1 when eval_every > 0")
        if cfg.max_snapshots < 0:
            raise ValueError("max_snapshots must be >= 0 (0 = keep all)")
        self.cfg = cfg
        self.config = config if config is not None else load_ruleset()
        torch.set_num_threads(cfg.torch_threads)
        torch.manual_seed(cfg.seed)
        self.rng = random.Random(cfg.seed)
        self.np_rng = np.random.default_rng(cfg.seed)
        self.encoder = ObservationEncoder(self.config)
        probe = Game(self.config)
        self.n_actions = probe.num_actions
        self.net = PolicyValueNet(self.encoder.dim, self.n_actions, cfg.hidden)
        self.opt = torch.optim.Adam(self.net.parameters(), lr=cfg.lr, eps=1e-5)
        self.run_dir = Path(cfg.run_dir)
        self.run_dir.mkdir(parents=True, exist_ok=True)

        self.self_opp = Opponent("self", "self")
        self.pool = [Opponent("random", "random", agent=RandomAgent(self.config, seed=cfg.seed)),
                     Opponent("greedy", "greedy", agent=GreedyAgent(self.config))]
        self.update = 0
        self.env_steps = 0          # all actions taken in training games (both seats)
        self.learner_steps = 0      # recorded learner transitions
        self.games = 0
        self.seed_block = TRAIN_SEED_BASE + cfg.seed * TRAIN_SEEDS_PER_RUN
        self.next_seed = self.seed_block
        self.lr_anchor = (0, cfg.lr)  # LR decays linearly from here to lr * lr_final_frac
        self.results = defaultdict(lambda: deque(maxlen=500))  # opponent kind -> learner rewards
        self.best_eval = -1.0
        self.envs = [EnvSlot(Game(self.config)) for _ in range(cfg.num_envs)]
        for slot in self.envs:
            self._reset_env(slot)
        self._obs_buf = np.zeros((cfg.num_envs, self.encoder.dim), dtype=np.float32)

    # ------------------------------------------------------------------ env management
    def _reset_env(self, slot: EnvSlot) -> None:
        slot.game.reset(self.next_seed)
        self.next_seed += 1
        if self.rng.random() < self.cfg.self_play_prob:
            slot.opp, slot.learner_seats = self.self_opp, (0, 1)
        else:
            slot.opp = self.pool[self.rng.randrange(len(self.pool))]
            slot.learner_seats = (self.rng.randrange(2),)
            if slot.opp.agent is not None:
                slot.opp.agent.reset(None)
        slot.traj = {s: [] for s in slot.learner_seats}

    def _finish(self, slot: EnvSlot, out: list) -> int:
        w = slot.game.winner()
        n = 0
        for seat in slot.learner_seats:
            r = 0.0 if w == DRAW else (1.0 if w == seat else -1.0)
            traj = slot.traj[seat]
            if traj:
                out.append(self._process(traj, r))
                n += len(traj)
            if slot.opp.kind != "self":
                self.results[slot.opp.kind].append(r)
        if slot.opp.kind == "self":
            # record how often the first player wins in mirror games (a balance diagnostic)
            self.results["self_first"].append(0.0 if w == DRAW else (1.0 if w == slot.game.first_player else -1.0))
        self.games += 1
        return n

    def _process(self, traj: list, reward: float) -> dict:
        cfg = self.cfg
        T = len(traj)
        obs = np.stack([t[0] for t in traj])
        mask = np.stack([t[1] for t in traj])
        act = np.array([t[2] for t in traj], dtype=np.int64)
        logp = np.array([t[3] for t in traj], dtype=np.float32)
        val = np.array([t[4] for t in traj], dtype=np.float32)
        adv = np.zeros(T, dtype=np.float32)
        last, next_v = 0.0, 0.0
        for t in range(T - 1, -1, -1):
            rew = reward if t == T - 1 else 0.0
            delta = rew + cfg.gamma * next_v - val[t]
            last = delta + cfg.gamma * cfg.gae_lambda * last
            adv[t] = last
            next_v = val[t]
        return {"obs": obs, "mask": mask, "act": act, "logp": logp, "val": val, "adv": adv, "ret": adv + val}

    # ------------------------------------------------------------------ acting
    def _net_act(self, net: PolicyValueNet, idxs: list, record: bool, actions: list) -> None:
        X = self._obs_buf[:len(idxs)]
        X[:] = 0.0
        M = np.zeros((len(idxs), self.n_actions), dtype=bool)
        enc = self.encoder
        for r, i in enumerate(idxs):
            g = self.envs[i].game
            g.legal_mask(out=M[r])
            enc.encode_into(g.observe(g.current), X[r], M[r])
        with torch.no_grad():
            a, logp, v = net.act(torch.from_numpy(X), torch.from_numpy(M))
        a, logp, v = a.numpy(), logp.numpy(), v.numpy()
        for r, i in enumerate(idxs):
            actions[i] = int(a[r])
            if record:
                slot = self.envs[i]
                slot.traj[slot.game.current].append((X[r].copy(), M[r], int(a[r]), float(logp[r]), float(v[r])))

    def _snapshot_act(self, policy: NumpyPolicy, idxs: list, actions: list) -> None:
        """Sample actions for a frozen snapshot with numpy (Gumbel-max over masked logits)."""
        X = self._obs_buf[:len(idxs)]
        X[:] = 0.0
        M = np.zeros((len(idxs), self.n_actions), dtype=bool)
        for r, i in enumerate(idxs):
            g = self.envs[i].game
            g.legal_mask(out=M[r])
            self.encoder.encode_into(g.observe(g.current), X[r], M[r])
        logits = np.where(M, policy.logits(X), -np.inf)
        a = np.argmax(logits + self.np_rng.gumbel(size=logits.shape), axis=1)
        for r, i in enumerate(idxs):
            actions[i] = int(a[r])

    def collect(self) -> list:
        """Run envs until at least `batch_steps` learner transitions from finished games exist."""
        out, collected = [], 0
        envs = self.envs
        actions = [0] * len(envs)
        self.net.eval()
        while collected < self.cfg.batch_steps:
            learner_idx, net_groups = [], defaultdict(list)
            for i, slot in enumerate(envs):
                g = slot.game
                legal = g.legal_actions()
                if len(legal) == 1:            # forced END_TURN: no decision to learn from
                    actions[i] = legal[0]
                elif g.current in slot.learner_seats:
                    learner_idx.append(i)
                elif slot.opp.policy is not None:
                    net_groups[id(slot.opp)].append(i)
                else:
                    actions[i] = slot.opp.agent.act(g.observe(g.current), legal)
            if learner_idx:
                self._net_act(self.net, learner_idx, True, actions)
            for idxs in net_groups.values():
                self._snapshot_act(envs[idxs[0]].opp.policy, idxs, actions)
            for i, slot in enumerate(envs):
                slot.game.step(actions[i])
                self.env_steps += 1
                if slot.game.done:
                    collected += self._finish(slot, out)
                    self._reset_env(slot)
        self.learner_steps += collected
        return out

    # ------------------------------------------------------------------ learning
    def learn(self, batch: list) -> dict:
        cfg = self.cfg
        cat = {k: torch.from_numpy(np.concatenate([b[k] for b in batch])) for k in batch[0]}
        N = cat["act"].shape[0]
        adv_all = cat["adv"]
        cat["adv_norm"] = (adv_all - adv_all.mean()) / (adv_all.std() + 1e-8)
        n_mb = max(1, round(N / cfg.minibatch))  # near-equal minibatches (no tiny remainder)
        lr = self.lr_at(self.update)
        for group in self.opt.param_groups:
            group["lr"] = lr
        self.net.train()
        stats = defaultdict(list)
        for epoch in range(cfg.epochs):
            kls = []
            for idx in torch.randperm(N).chunk(n_mb):
                logp, ent, v = self.net.evaluate(cat["obs"][idx], cat["mask"][idx], cat["act"][idx])
                log_ratio = logp - cat["logp"][idx]
                ratio = log_ratio.exp()
                adv = cat["adv_norm"][idx]
                pg_loss = torch.max(-adv * ratio, -adv * ratio.clamp(1 - cfg.clip, 1 + cfg.clip)).mean()
                v_loss = 0.5 * (v - cat["ret"][idx]).pow(2).mean()
                ent_mean = ent.mean()
                loss = pg_loss + cfg.vf_coef * v_loss - cfg.ent_coef * ent_mean
                if not torch.isfinite(loss):
                    stats["skipped_nonfinite"].append(1.0)
                    continue
                self.opt.zero_grad(set_to_none=True)
                loss.backward()
                torch.nn.utils.clip_grad_norm_(self.net.parameters(), cfg.max_grad_norm)
                self.opt.step()
                with torch.no_grad():
                    kl = ((ratio - 1) - log_ratio).mean().item()
                    clipfrac = ((ratio - 1).abs() > cfg.clip).float().mean().item()
                kls.append(kl)
                stats["pg_loss"].append(pg_loss.item())
                stats["v_loss"].append(v_loss.item())
                stats["entropy"].append(ent_mean.item())
                stats["kl"].append(kl)
                stats["clipfrac"].append(clipfrac)
            stats["epochs"] = [epoch + 1]
            if cfg.target_kl and kls and np.mean(kls) > cfg.target_kl:
                break
        with torch.no_grad():
            var_y = cat["ret"].var()
            explained = 1 - (cat["ret"] - cat["val"]).var() / (var_y + 1e-8)
        out = {k: float(np.mean(v)) for k, v in stats.items()}
        out.update(lr=lr, batch=N, explained_var=float(explained))
        return out

    def lr_at(self, update: int) -> float:
        """Linear decay from the anchor (start, or the resume point) to lr * lr_final_frac."""
        cfg = self.cfg
        u0, lr0 = self.lr_anchor
        lr_end = cfg.lr * cfg.lr_final_frac
        frac = min(1.0, (update - u0) / max(1, cfg.total_updates - u0))
        return lr0 + (lr_end - lr0) * frac

    # ------------------------------------------------------------------ pool, eval, checkpoints
    def _add_snapshot(self, path: Path) -> None:
        snap = copy.deepcopy(self.net).eval()
        for p in snap.parameters():
            p.requires_grad_(False)
        self.pool.append(Opponent("snapshot", f"snap_{self.update:05d}", net=snap, path=str(Path(path).resolve())))
        self._prune_snapshots()

    def _prune_snapshots(self) -> None:
        """Keep the newest `max_snapshots` snapshots (0 = all); random and greedy always stay."""
        snaps = [o for o in self.pool if o.kind == "snapshot"]
        excess = len(snaps) - self.cfg.max_snapshots if self.cfg.max_snapshots else 0
        for o in snaps[:max(0, excess)]:
            self.pool.remove(o)

    def quick_eval(self, n_deals: int, opponent: str = "greedy", deterministic: bool = False) -> dict:
        """Vectorized duplicate games of the current policy vs a scripted opponent."""
        agent = GreedyAgent(self.config) if opponent == "greedy" else RandomAgent(self.config, seed=0)
        jobs = [(QUICK_EVAL_SEED_BASE + d, seat) for d in range(n_deals) for seat in (0, 1)]
        wins = draws = 0
        seat_wins = [0, 0]
        width = self.cfg.num_envs
        self.net.eval()
        for start in range(0, len(jobs), width):
            chunk = jobs[start:start + width]
            games = []
            for seed, seat in chunk:
                g = Game(self.config)
                g.reset(seed)
                games.append((g, seat))
            while True:
                live = [(g, s) for g, s in games if not g.done]
                if not live:
                    break
                mine = [(g, s) for g, s in live if g.current == s]
                for g, s in live:
                    if g.current != s:
                        g.step(agent.act(g.observe(g.current), g.legal_actions()))
                if mine:
                    X = np.zeros((len(mine), self.encoder.dim), dtype=np.float32)
                    M = np.zeros((len(mine), self.n_actions), dtype=bool)
                    for r, (g, s) in enumerate(mine):
                        g.legal_mask(out=M[r])
                        self.encoder.encode_into(g.observe(s), X[r], M[r])
                    a, _, _ = self.net.act(torch.from_numpy(X), torch.from_numpy(M), deterministic)
                    for r, (g, s) in enumerate(mine):
                        g.step(int(a[r]))
            for g, s in games:
                w = g.winner()
                if w == s:
                    wins += 1
                    seat_wins[s] += 1
                elif w == DRAW:
                    draws += 1
        n = len(jobs)
        return {"win_rate": wins / n, "draw_rate": draws / n,
                "seat0_win_rate": seat_wins[0] / (n // 2), "seat1_win_rate": seat_wins[1] / (n // 2)}

    def checkpoint(self, path: Path, with_optimizer: bool = False) -> None:
        state = {"model": self.net.state_dict(), "net": self.net.spec(), "update": self.update,
                 "env_steps": self.env_steps, "learner_steps": self.learner_steps, "games": self.games,
                 "args": asdict(self.cfg)}
        if with_optimizer:
            state["optimizer"] = self.opt.state_dict()
            state["lr"] = self.lr_at(self.update)
            # snapshot weights already live in their ckpt_*.pt files; store references only
            # (relative to the run dir, so a run directory can be moved as a whole)
            run_dir = self.run_dir.resolve()
            state["snapshots"] = [(o.name, os.path.relpath(o.path, run_dir)) for o in self.pool if o.kind == "snapshot"]
            state["next_seed"] = self.next_seed
            state["best_eval"] = self.best_eval
            state["rng"] = self.rng.getstate()
        tmp = path.with_suffix(".tmp")
        torch.save(state, tmp)
        tmp.replace(path)

    def resume(self, path: str) -> None:
        state = torch.load(path, map_location="cpu", weights_only=False)
        if state["net"] != self.net.spec():
            raise ValueError(f"checkpoint network {state['net']} does not match this config {self.net.spec()}; "
                             "the architecture (--hidden) is fixed by the checkpoint")
        self.net.load_state_dict(state["model"])
        if "optimizer" in state:
            self.opt.load_state_dict(state["optimizer"])
        self.update = state["update"]
        self.env_steps = state.get("env_steps", 0)
        self.learner_steps = state.get("learner_steps", 0)
        self.games = state.get("games", 0)
        # ckpt_*.pt / best.pt carry no seed counter: continue in the upper half of this run's own block
        self.next_seed = state.get("next_seed", self.seed_block + TRAIN_SEEDS_PER_RUN // 2 + self.games)
        if not self.seed_block <= self.next_seed < self.seed_block + TRAIN_SEEDS_PER_RUN:
            raise ValueError("resumed seed counter falls outside this run's seed block; pass the run's --seed")
        self.best_eval = state.get("best_eval", -1.0)
        saved_lr = state.get("lr", self.lr_at(self.update))
        saved_base_lr = state.get("args", {}).get("lr", self.cfg.lr)
        if saved_base_lr and self.cfg.lr != saved_base_lr:  # --lr given on resume rescales the schedule
            saved_lr *= self.cfg.lr / saved_base_lr
        self.lr_anchor = (self.update, saved_lr)
        if "rng" in state:
            self.rng.setstate(state["rng"])
        src_dir = Path(path).resolve().parent
        for name, rel in state.get("snapshots", []):
            snap_path = (src_dir / rel).resolve()
            if not snap_path.is_file():
                warnings.warn(f"snapshot {name} not found at {snap_path}; dropped from the pool")
                continue
            ckpt = torch.load(snap_path, map_location="cpu", weights_only=False)
            spec = ckpt["net"]
            snap = PolicyValueNet(spec["obs_dim"], spec["n_actions"], spec["hidden"])
            snap.load_state_dict(ckpt["model"])
            snap.eval()
            self.pool.append(Opponent("snapshot", name, net=snap, path=str(snap_path)))
        self._prune_snapshots()
        for slot in self.envs:
            self._reset_env(slot)

    # ------------------------------------------------------------------ main loop
    def train(self, log=print) -> None:
        cfg = self.cfg
        with open(self.run_dir / "config.json", "w", encoding="utf-8") as f:
            json.dump(asdict(cfg), f, indent=2)
        metrics_file = open(self.run_dir / "metrics.jsonl", "a", encoding="utf-8")
        t_start = time.time()
        while self.update < cfg.total_updates:
            t0 = time.time()
            batch = self.collect()
            t1 = time.time()
            stats = self.learn(batch)
            t2 = time.time()
            self.update += 1
            row = {"update": self.update, "env_steps": self.env_steps, "learner_steps": self.learner_steps,
                   "games": self.games, "collect_s": round(t1 - t0, 2), "learn_s": round(t2 - t1, 2),
                   "steps_per_s": round(sum(len(b["act"]) for b in batch) / max(1e-9, t1 - t0), 1),
                   "elapsed_min": round((t2 - t_start) / 60, 2), "pool": len(self.pool), **stats}
            for kind, rs in self.results.items():
                if rs:
                    row[f"train_vs_{kind}"] = round(float(np.mean([r > 0 for r in rs])), 3)
            if self.update % cfg.snapshot_every == 0:
                path = self.run_dir / f"ckpt_{self.update:05d}.pt"
                self.checkpoint(path)
                self._add_snapshot(path)
            if cfg.eval_every and self.update % cfg.eval_every == 0:
                ev = self.quick_eval(cfg.eval_deals)
                row.update({f"eval_greedy_{k}": round(v, 3) for k, v in ev.items()})
                if ev["win_rate"] > self.best_eval:
                    self.best_eval = ev["win_rate"]
                    self.checkpoint(self.run_dir / "best.pt")
            self.checkpoint(self.run_dir / "latest.pt", with_optimizer=True)
            metrics_file.write(json.dumps(row) + "\n")
            metrics_file.flush()
            log(format_row(row))
        metrics_file.close()


def format_row(row: dict) -> str:
    keys = ["update", "env_steps", "games", "steps_per_s", "entropy", "kl", "clipfrac", "v_loss",
            "explained_var", "train_vs_random", "train_vs_greedy", "train_vs_snapshot", "train_vs_self_first",
            "eval_greedy_win_rate", "elapsed_min"]
    parts = []
    for k in keys:
        if k in row:
            v = row[k]
            parts.append(f"{k}={v:.3f}" if isinstance(v, float) else f"{k}={v}")
    return " ".join(parts)
